# -*- coding: utf-8 -*-
"""Ejercicio 2.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5Ayodw9c25kUXhV70LW2Aec99quOWp1

Ejercicio 2.4
"""

import math


class Circulo:
    def __init__(self, radio: float):
        self.radio = radio  # cm

    def calcular_area(self) -> float:
        return math.pi * self.radio ** 2

    def calcular_perimetro(self) -> float:
        return 2 * math.pi * self.radio


class Rectangulo:
    def __init__(self, base: float, altura: float):
        self.base = base      # cm
        self.altura = altura  # cm

    def calcular_area(self) -> float:
        return self.base * self.altura

    def calcular_perimetro(self) -> float:
        return 2 * (self.base + self.altura)


class Cuadrado:
    def __init__(self, lado: float):
        self.lado = lado  # cm

    def calcular_area(self) -> float:
        return self.lado ** 2

    def calcular_perimetro(self) -> float:
        return 4 * self.lado


class TrianguloRectangulo:
    def __init__(self, base: float, altura: float):
        self.base = base      # cm (cateto)
        self.altura = altura  # cm (cateto)

    def calcular_area(self) -> float:
        return self.base * self.altura / 2

    def calcular_hipotenusa(self) -> float:
        return math.sqrt(self.base ** 2 + self.altura ** 2)

    def calcular_perimetro(self) -> float:
        return self.base + self.altura + self.calcular_hipotenusa()

    def determinar_tipo(self) -> str:
        """Clasifica el triángulo según la longitud de sus tres lados."""
        a, b, c = self.base, self.altura, self.calcular_hipotenusa()
        if math.isclose(a, b) and math.isclose(b, c):
            return "Equilátero"
        if math.isclose(a, b) or math.isclose(a, c) or math.isclose(b, c):
            return "Isósceles"
        return "Escaleno"


class Rombo:
    """Nueva clase: se define con sus dos diagonales."""

    def __init__(self, diagonal_mayor: float, diagonal_menor: float):
        self.diagonal_mayor = diagonal_mayor  # cm
        self.diagonal_menor = diagonal_menor  # cm

    def calcular_lado(self) -> float:
        semi_mayor = self.diagonal_mayor / 2
        semi_menor = self.diagonal_menor / 2
        return math.sqrt(semi_mayor ** 2 + semi_menor ** 2)

    def calcular_area(self) -> float:
        return self.diagonal_mayor * self.diagonal_menor / 2

    def calcular_perimetro(self) -> float:
        return 4 * self.calcular_lado()


class Trapecio:
    """Nueva clase: bases, altura y los dos lados no paralelos."""

    def __init__(self, base_mayor: float, base_menor: float, altura: float,
                 lado_izquierdo: float, lado_derecho: float):
        self.base_mayor = base_mayor            # cm
        self.base_menor = base_menor            # cm
        self.altura = altura                    # cm
        self.lado_izquierdo = lado_izquierdo    # cm
        self.lado_derecho = lado_derecho        # cm

    def calcular_area(self) -> float:
        return (self.base_mayor + self.base_menor) * self.altura / 2

    def calcular_perimetro(self) -> float:
        return (self.base_mayor + self.base_menor
                + self.lado_izquierdo + self.lado_derecho)


def main() -> None:
    circulo = Circulo(5)
    rectangulo = Rectangulo(6, 4)
    cuadrado = Cuadrado(3)
    triangulo = TrianguloRectangulo(3, 4)
    rombo = Rombo(8, 6)
    trapecio = Trapecio(8, 4, 3, 3, 5)

    figuras = [("Círculo", circulo), ("Rectángulo", rectangulo),
               ("Cuadrado", cuadrado), ("Triángulo rectángulo", triangulo),
               ("Rombo", rombo), ("Trapecio", trapecio)]
    for nombre, figura in figuras:
        print(f"{nombre}: área = {figura.calcular_area():.2f} cm², "
              f"perímetro = {figura.calcular_perimetro():.2f} cm")
    print(f"Hipotenusa del triángulo = {triangulo.calcular_hipotenusa():.2f} cm")
    print(f"Tipo de triángulo = {triangulo.determinar_tipo()}")


if __name__ == "__main__":
    main()