# -*- coding: utf-8 -*-
"""Ejercicio 2.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5Ayodw9c25kUXhV70LW2Aec99quOWp1

Ejercicio 2.3
```
# Esto tiene formato de código
```
"""

from enum import Enum

VALOR_MULTA_INICIAL = 100_000   # pesos, primera infracción
INCREMENTO_MULTA = 50_000       # pesos que se suman por cada infracción adicional


class TipoCombustible(Enum):
    GASOLINA = "Gasolina"
    BIOETANOL = "Bioetanol"
    DIESEL = "Diésel"
    BIODIESEL = "Biodiésel"
    GAS_NATURAL = "Gas natural"


class TipoAutomovil(Enum):
    CIUDAD = "Carro de ciudad"
    SUBCOMPACTO = "Subcompacto"
    COMPACTO = "Compacto"
    FAMILIAR = "Familiar"
    EJECUTIVO = "Ejecutivo"
    SUV = "SUV"


class Color(Enum):
    BLANCO = "Blanco"
    NEGRO = "Negro"
    ROJO = "Rojo"
    NARANJA = "Naranja"
    AMARILLO = "Amarillo"
    VERDE = "Verde"
    AZUL = "Azul"
    VIOLETA = "Violeta"


class Automovil:
    """Modela un automóvil con su estado de velocidad y sus multas."""

    def __init__(self, marca: str, modelo: int, motor: float,
                 tipo_combustible: TipoCombustible, tipo_automovil: TipoAutomovil,
                 numero_puertas: int, cantidad_asientos: int,
                 velocidad_maxima: int, color: Color, es_automatico: bool):
        self._marca = marca
        self._modelo = modelo                    # año de fabricación
        self._motor = motor                      # cilindraje en litros
        self._tipo_combustible = tipo_combustible
        self._tipo_automovil = tipo_automovil
        self._numero_puertas = numero_puertas
        self._cantidad_asientos = cantidad_asientos
        self._velocidad_maxima = velocidad_maxima  # km/h
        self._color = color
        self._es_automatico = es_automatico      # nuevo atributo
        self._velocidad_actual = 0               # km/h
        self._multas: list[float] = []           # valor de cada multa

    # ---------- Métodos get y set (propiedades de Python) ----------
    @property
    def marca(self) -> str:
        return self._marca

    @marca.setter
    def marca(self, valor: str) -> None:
        self._marca = valor

    @property
    def modelo(self) -> int:
        return self._modelo

    @modelo.setter
    def modelo(self, valor: int) -> None:
        self._modelo = valor

    @property
    def motor(self) -> float:
        return self._motor

    @motor.setter
    def motor(self, valor: float) -> None:
        self._motor = valor

    @property
    def tipo_combustible(self) -> TipoCombustible:
        return self._tipo_combustible

    @tipo_combustible.setter
    def tipo_combustible(self, valor: TipoCombustible) -> None:
        self._tipo_combustible = valor

    @property
    def tipo_automovil(self) -> TipoAutomovil:
        return self._tipo_automovil

    @tipo_automovil.setter
    def tipo_automovil(self, valor: TipoAutomovil) -> None:
        self._tipo_automovil = valor

    @property
    def numero_puertas(self) -> int:
        return self._numero_puertas

    @numero_puertas.setter
    def numero_puertas(self, valor: int) -> None:
        self._numero_puertas = valor

    @property
    def cantidad_asientos(self) -> int:
        return self._cantidad_asientos

    @cantidad_asientos.setter
    def cantidad_asientos(self, valor: int) -> None:
        self._cantidad_asientos = valor

    @property
    def velocidad_maxima(self) -> int:
        return self._velocidad_maxima

    @velocidad_maxima.setter
    def velocidad_maxima(self, valor: int) -> None:
        self._velocidad_maxima = valor

    @property
    def color(self) -> Color:
        return self._color

    @color.setter
    def color(self, valor: Color) -> None:
        self._color = valor

    @property
    def es_automatico(self) -> bool:
        return self._es_automatico

    @es_automatico.setter
    def es_automatico(self, valor: bool) -> None:
        self._es_automatico = valor

    @property
    def velocidad_actual(self) -> int:
        return self._velocidad_actual

    @velocidad_actual.setter
    def velocidad_actual(self, valor: int) -> None:
        if valor < 0 or valor > self._velocidad_maxima:
            print("Velocidad no válida: debe estar entre 0 y la velocidad máxima.")
        else:
            self._velocidad_actual = valor

    # ---------- Comportamiento ----------
    def acelerar(self, incremento: int) -> None:
        """Aumenta la velocidad; si supera el máximo, no acelera y genera multa."""
        if self._velocidad_actual + incremento > self._velocidad_maxima:
            valor = VALOR_MULTA_INICIAL + INCREMENTO_MULTA * len(self._multas)
            self._multas.append(valor)
            print(f"No se puede superar la velocidad máxima "
                  f"({self._velocidad_maxima} km/h). Multa generada: ${valor:,.0f}")
        else:
            self._velocidad_actual += incremento

    def desacelerar(self, decremento: int) -> None:
        """Disminuye la velocidad; no permite velocidades negativas."""
        if self._velocidad_actual - decremento < 0:
            print("No se puede desacelerar a una velocidad negativa.")
        else:
            self._velocidad_actual -= decremento

    def frenar(self) -> None:
        """Coloca la velocidad actual en cero."""
        self._velocidad_actual = 0

    def calcular_tiempo_llegada(self, distancia_km: float) -> float | None:
        """Tiempo estimado (horas) = distancia / velocidad actual."""
        if self._velocidad_actual == 0:
            print("El automóvil está detenido: no se puede estimar el tiempo.")
            return None
        return distancia_km / self._velocidad_actual

    def tiene_multas(self) -> bool:
        return len(self._multas) > 0

    def calcular_total_multas(self) -> float:
        return sum(self._multas)

    def imprimir(self) -> None:
        """Imprime en pantalla los valores de los atributos del automóvil."""
        print(f"Marca = {self._marca}")
        print(f"Modelo = {self._modelo}")
        print(f"Motor = {self._motor} L")
        print(f"Tipo de combustible = {self._tipo_combustible.value}")
        print(f"Tipo de automóvil = {self._tipo_automovil.value}")
        print(f"Número de puertas = {self._numero_puertas}")
        print(f"Cantidad de asientos = {self._cantidad_asientos}")
        print(f"Velocidad máxima = {self._velocidad_maxima} km/h")
        print(f"Color = {self._color.value}")
        print(f"Automático = {self._es_automatico}")
        print(f"Velocidad actual = {self._velocidad_actual} km/h")
        total = self.calcular_total_multas()
        print(f"Multas = {len(self._multas)} (total ${total:,.0f})")


def main() -> None:
    auto = Automovil("Renault", 2022, 1.6, TipoCombustible.GASOLINA,
                     TipoAutomovil.COMPACTO, 4, 5, 180, Color.ROJO, True)
    auto.imprimir()
    print()

    auto.velocidad_actual = 100
    print(f"Velocidad actual: {auto.velocidad_actual} km/h")
    auto.acelerar(20)
    print(f"Velocidad actual: {auto.velocidad_actual} km/h")
    auto.desacelerar(50)
    print(f"Velocidad actual: {auto.velocidad_actual} km/h")
    horas = auto.calcular_tiempo_llegada(200)
    print(f"Tiempo estimado para 200 km: {horas:.2f} h")
    auto.frenar()
    print(f"Velocidad actual: {auto.velocidad_actual} km/h")
    print()

    # Ejercicios propuestos: multas por intentar superar la velocidad máxima
    auto.velocidad_actual = 150
    auto.acelerar(50)
    auto.acelerar(50)
    print(f"¿Tiene multas? {auto.tiene_multas()}")
    print(f"Total de multas: ${auto.calcular_total_multas():,.0f}")


if __name__ == "__main__":
    main()