# -*- coding: utf-8 -*-
"""Ejercicio 2.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5Ayodw9c25kUXhV70LW2Aec99quOWp1

Ejercicio 2.2

```
# Esto tiene formato de código
```
"""

from enum import Enum

UA_EN_MILLONES_KM = 149.59787   # 1 UA = 149 597 870 km
LIMITE_CINTURON_UA = 3.4        # el cinturón de asteroides va de 2.1 a 3.4 UA


class TipoPlaneta(Enum):
    GASEOSO = "Gaseoso"
    TERRESTRE = "Terrestre"
    ENANO = "Enano"


class Planeta:
    """Modela un planeta del sistema solar."""

    def __init__(self, nombre: str = None, cantidad_satelites: int = 0,
                 masa: float = 0.0, volumen: float = 0.0, diametro: int = 0,
                 distancia_sol: int = 0, tipo: TipoPlaneta = None,
                 es_observable: bool = False, periodo_orbital: float = 0.0,
                 periodo_rotacion: float = 0.0):
        self.nombre = nombre
        self.cantidad_satelites = cantidad_satelites
        self.masa = masa                          # kg
        self.volumen = volumen                    # km³
        self.diametro = diametro                  # km
        self.distancia_sol = distancia_sol        # millones de km
        self.tipo = tipo
        self.es_observable = es_observable
        self.periodo_orbital = periodo_orbital    # nuevo atributo: años
        self.periodo_rotacion = periodo_rotacion  # nuevo atributo: días

    def imprimir(self) -> None:
        """Imprime en pantalla los valores de los atributos del planeta."""
        print(f"Nombre del planeta = {self.nombre}")
        print(f"Cantidad de satélites = {self.cantidad_satelites}")
        print(f"Masa del planeta = {self.masa:.3e} kg")
        print(f"Volumen del planeta = {self.volumen:.3e} km³")
        print(f"Diámetro del planeta = {self.diametro} km")
        print(f"Distancia al Sol = {self.distancia_sol} millones de km")
        print(f"Tipo de planeta = {self.tipo.value}")
        print(f"Es observable = {self.es_observable}")
        print(f"Periodo orbital = {self.periodo_orbital} años")
        print(f"Periodo de rotación = {self.periodo_rotacion} días")

    def calcular_densidad(self) -> float:
        """Devuelve la densidad (masa / volumen) en kg/km³."""
        if self.volumen == 0:
            return 0.0
        return self.masa / self.volumen

    def es_exterior(self) -> bool:
        """Un planeta es exterior si está más allá del cinturón de asteroides."""
        return self.distancia_sol > LIMITE_CINTURON_UA * UA_EN_MILLONES_KM


def main() -> None:
    tierra = Planeta("Tierra", 1, 5.97e24, 1.08321e12, 12756, 150,
                     TipoPlaneta.TERRESTRE, True, 1.0, 0.99)
    jupiter = Planeta("Júpiter", 79, 1.898e27, 1.43128e15, 142984, 778,
                      TipoPlaneta.GASEOSO, True, 11.86, 0.41)
    for planeta in (tierra, jupiter):
        planeta.imprimir()
        print(f"Densidad = {planeta.calcular_densidad():.3e} kg/km³")
        print(f"¿Es planeta exterior? {planeta.es_exterior()}")
        print()


if __name__ == "__main__":
    main()