# -*- coding: utf-8 -*-
"""Ejercicio 2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5Ayodw9c25kUXhV70LW2Aec99quOWp1

Ejercicio 2.1

```
# Esto tiene formato de código
```
"""

class Persona:
    """Modela una persona con sus datos de identificación básicos."""

    def __init__(self, nombre: str, apellidos: str, numero_documento_identidad: str,
                 año_nacimiento: int, pais_nacimiento: str, genero: str):
        if genero not in ("H", "M"):
            raise ValueError("El género debe ser 'H' o 'M'.")
        self.nombre = nombre
        self.apellidos = apellidos
        self.numero_documento_identidad = numero_documento_identidad
        self.año_nacimiento = año_nacimiento
        self.pais_nacimiento = pais_nacimiento   # nuevo atributo
        self.genero = genero                     # nuevo atributo ('H' o 'M')

    def imprimir(self) -> None:
        """Imprime en pantalla los valores de los atributos de la persona."""
        print(f"Nombre = {self.nombre}")
        print(f"Apellidos = {self.apellidos}")
        print("Número de documento de identidad = "
              f"{self.numero_documento_identidad}")
        print(f"Año de nacimiento = {self.año_nacimiento}")
        print(f"País de nacimiento = {self.pais_nacimiento}")
        print(f"Género = {self.genero}")
        print()


def main() -> None:
    p1 = Persona("Pedro", "Pérez", "1053121010", 1998, "Colombia", "H")
    p2 = Persona("María", "León", "1053223344", 2001, "México", "M")
    p1.imprimir()
    p2.imprimir()


if __name__ == "__main__":
    main()