# -*- coding: utf-8 -*-
"""Ejercicio 2.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5Ayodw9c25kUXhV70LW2Aec99quOWp1

Ejercicio 2.5
"""

from enum import Enum


class TipoCuenta(Enum):
    AHORROS = "Ahorros"
    CORRIENTE = "Corriente"


class CuentaBancaria:
    """Modela una cuenta bancaria; el saldo inicial siempre es cero."""

    def __init__(self, nombres: str, apellidos: str, numero_cuenta: str,
                 tipo_cuenta: TipoCuenta, tasa_interes_mensual: float):
        self.nombres = nombres
        self.apellidos = apellidos
        self.numero_cuenta = numero_cuenta
        self.tipo_cuenta = tipo_cuenta
        self.saldo = 0.0
        self.tasa_interes_mensual = tasa_interes_mensual  # nuevo atributo (en %)

    def imprimir(self) -> None:
        print(f"Titular = {self.nombres} {self.apellidos}")
        print(f"Número de cuenta = {self.numero_cuenta}")
        print(f"Tipo de cuenta = {self.tipo_cuenta.value}")
        print(f"Saldo = ${self.saldo:,.2f}")
        print(f"Interés mensual = {self.tasa_interes_mensual}%")

    def consultar_saldo(self) -> float:
        return self.saldo

    def consignar(self, valor: float) -> None:
        if valor <= 0:
            print("El valor a consignar debe ser mayor que cero.")
            return
        self.saldo += valor

    def retirar(self, valor: float) -> None:
        if valor <= 0:
            print("El valor a retirar debe ser mayor que cero.")
        elif valor > self.saldo:
            print("Fondos insuficientes: el retiro supera el saldo actual.")
        else:
            self.saldo -= valor

    def calcular_nuevo_saldo(self) -> float:
        """Devuelve el saldo con el interés mensual aplicado (no lo modifica)."""
        return self.saldo * (1 + self.tasa_interes_mensual / 100)


def main() -> None:
    cuenta = CuentaBancaria("Ana", "Gómez", "123-456-789", TipoCuenta.AHORROS, 1.5)
    cuenta.imprimir()
    cuenta.consignar(1_000_000)
    print(f"Saldo tras consignar: ${cuenta.consultar_saldo():,.2f}")
    cuenta.retirar(200_000)
    print(f"Saldo tras retirar: ${cuenta.consultar_saldo():,.2f}")
    cuenta.retirar(5_000_000)
    print(f"Saldo con interés mensual: ${cuenta.calcular_nuevo_saldo():,.2f}")


if __name__ == "__main__":
    main()